-- Run this in Supabase SQL Editor

-- 1. Create menu_items table
CREATE TABLE menu_items (
  id BIGSERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  price NUMERIC NOT NULL DEFAULT 0,
  seasonal BOOLEAN NOT NULL DEFAULT false,
  available BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE menu_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all" ON menu_items FOR ALL USING (true) WITH CHECK (true);

-- 2. Seed all menu items
INSERT INTO menu_items (name, category, price, seasonal, available) VALUES
-- Breakfast
('Appam', 'Breakfast', 18, false, true),
('Idiappam', 'Breakfast', 18, false, true),
('Puttu', 'Breakfast', 60, false, true),
('Chappathi', 'Breakfast', 18, false, true),
('Porotta', 'Breakfast', 20, false, true),
('Wheat Porotta', 'Breakfast', 25, false, true),
('Nool Porotta', 'Breakfast', 35, false, true),
('Poori Baji', 'Breakfast', 80, false, true),
('Neer Dosa', 'Breakfast', 18, false, true),
('Set Dosa', 'Breakfast', 70, false, true),
('Plain Dosa', 'Breakfast', 60, false, true),
('Masala Dosa', 'Breakfast', 80, false, true),
('Ghee Roast', 'Breakfast', 90, false, true),
('Onion Dosa', 'Breakfast', 90, false, true),
('Egg Dosa', 'Breakfast', 90, false, true),
('Kadala Curry', 'Breakfast', 70, false, true),
('Greenpeas Curry', 'Breakfast', 80, false, true),
('Cherupayar Curry', 'Breakfast', 70, false, true),
('Egg Curry', 'Breakfast', 70, false, true),
('Egg Roast', 'Breakfast', 90, false, true),
('Aloobaji', 'Breakfast', 70, false, true),
('Veg Kuruma', 'Breakfast', 90, false, true),

-- Rice & Biriyani
('Kerala Meals', 'Rice & Biriyani', 100, false, true),
('Fish Curry Meals', 'Rice & Biriyani', 180, false, true),
('Chicken Curry Meals', 'Rice & Biriyani', 170, false, true),
('Pothichoru Veg', 'Rice & Biriyani', 120, false, true),
('Pothichoru Egg', 'Rice & Biriyani', 150, false, true),
('Pothichoru Fish', 'Rice & Biriyani', 200, false, true),
('Pothichoru Chicken', 'Rice & Biriyani', 190, false, true),
('Pothichoru Pothu', 'Rice & Biriyani', 220, false, true),
('Ghee Rice', 'Rice & Biriyani', 110, false, true),
('Biriyani Rice', 'Rice & Biriyani', 120, false, true),
('Egg Biriyani', 'Rice & Biriyani', 160, false, true),
('Veg Biriyani', 'Rice & Biriyani', 150, false, true),
('Paneer Biriyani', 'Rice & Biriyani', 210, false, true),
('Chicken Biriyani (Half)', 'Rice & Biriyani', 140, false, true),
('Chicken Biriyani (Full)', 'Rice & Biriyani', 200, false, true),
('Chicken Pothi Biriyani', 'Rice & Biriyani', 220, false, true),
('Pothu Biriyani (Half)', 'Rice & Biriyani', 150, false, true),
('Pothu Biriyani (Full)', 'Rice & Biriyani', 230, false, true),
('Pothu Pothi Biriyani', 'Rice & Biriyani', 250, false, true),
('Mutton Biriyani', 'Rice & Biriyani', 380, false, true),
('Kada Biriyani', 'Rice & Biriyani', 260, false, true),

-- Special
('Kappa', 'Special', 90, false, true),
('Kappa Mix Veg', 'Special', 160, false, true),
('Kappa Mix Fish', 'Special', 210, false, true),
('Kappa Mix Chicken', 'Special', 200, false, true),
('Kappa Mix Pothu', 'Special', 230, false, true),
('Puttu Mix Egg', 'Special', 160, false, true),
('Puttu Mix Chicken', 'Special', 210, false, true),
('Puttu Mix Pothu', 'Special', 240, false, true),
('Kizhi Porotta Chicken', 'Special', 210, false, true),
('Kizhi Porotta Pothu', 'Special', 240, false, true),
('Pothi Porotta Chicken', 'Special', 210, false, true),
('Pothi Porotta Pothu', 'Special', 240, false, true),
('Kothu Porotta Veg', 'Special', 160, false, true),
('Kothu Porotta Egg', 'Special', 160, false, true),
('Kothu Porotta Chicken', 'Special', 210, false, true),
('Kothu Porotta Pothu', 'Special', 240, false, true),
('Pathal Mix Pothu', 'Special', 240, false, true),

-- Fish Fry & Curry
('Ayala Fry', 'Fish Fry & Curry', 0, true, true),
('Mathi Fry', 'Fish Fry & Curry', 0, true, true),
('Squid Fry', 'Fish Fry & Curry', 0, true, true),
('Choora Fry', 'Fish Fry & Curry', 0, true, true),
('Avoli Fry', 'Fish Fry & Curry', 0, true, true),
('Podimeen Fry', 'Fish Fry & Curry', 0, true, true),
('Neimeen Fry', 'Fish Fry & Curry', 0, true, true),
('Kilimeen Fry', 'Fish Fry & Curry', 0, true, true),
('Prawns Fry', 'Fish Fry & Curry', 0, true, true),
('Prawns Roast', 'Fish Fry & Curry', 0, true, true),
('Squid Roast', 'Fish Fry & Curry', 0, true, true),
('Ayala Mulakittath', 'Fish Fry & Curry', 0, true, true),
('Mathi Mulakittath', 'Fish Fry & Curry', 0, true, true),
('Choora Mulakittath', 'Fish Fry & Curry', 0, true, true),

-- Homely Special
('Kanji', 'Homely Special', 120, false, true),
('Kanji & Fish Fry', 'Homely Special', 0, true, true),
('Kanji & Chicken Fry', 'Homely Special', 200, false, true),
('Chatti Choru', 'Homely Special', 410, false, true),
('Bellari Pothu Fry', 'Homely Special', 270, false, true),
('Kanthari Pothu Fry', 'Homely Special', 270, false, true),

-- Non Veg Curry
('Chicken Varutharachath', 'Non Veg Curry', 200, false, true),
('Chicken Varattu', 'Non Veg Curry', 240, false, true),
('Chicken Kuruma', 'Non Veg Curry', 220, false, true),
('Chicken Roast', 'Non Veg Curry', 240, false, true),
('Chicken Chukka', 'Non Veg Curry', 240, false, true),
('Chicken Hyderabadi', 'Non Veg Curry', 250, false, true),
('Kada Roast', 'Non Veg Curry', 200, false, true),
('Kada Fry', 'Non Veg Curry', 180, false, true),
('BDF', 'Non Veg Curry', 300, false, true),
('Pothu Chilli', 'Non Veg Curry', 340, false, true),
('Chicken Masala', 'Non Veg Curry', 270, false, true),
('Thattukada Chicken Fry', 'Non Veg Curry', 170, false, true),
('Chicken Stew', 'Non Veg Curry', 220, false, true),
('Kadai Chicken', 'Non Veg Curry', 250, false, true),
('Pothu Roast (Half)', 'Non Veg Curry', 150, false, true),
('Pothu Roast (Full)', 'Non Veg Curry', 240, false, true),
('Pothu Fry (Half)', 'Non Veg Curry', 160, false, true),
('Pothu Fry (Full)', 'Non Veg Curry', 250, false, true),
('Mutton Roast', 'Non Veg Curry', 330, false, true),

-- Egg Special
('Egg Chilli', 'Egg Special', 170, false, true),
('Egg Manchurian', 'Egg Special', 170, false, true),
('Egg Masala Double', 'Egg Special', 150, false, true),
('Egg Burji', 'Egg Special', 110, false, true),
('Egg Omlet Single', 'Egg Special', 30, false, true),
('Bulls Eye Single', 'Egg Special', 25, false, true),
('Boiled Egg', 'Egg Special', 15, false, true),

-- Starters
('Gobi 65', 'Starters', 150, false, true),
('Gobi Manchurian', 'Starters', 140, false, true),
('Chilli Gobi', 'Starters', 150, false, true),
('Paneer 65', 'Starters', 220, false, true),
('Paneer Manchurian', 'Starters', 190, false, true),
('Paneer Chilli', 'Starters', 190, false, true),
('Paneer Pepper Dry', 'Starters', 200, false, true),
('Mushroom Chilli', 'Starters', 170, false, true),
('Mushroom Pepper Dry', 'Starters', 190, false, true),
('Mushroom Manchurian', 'Starters', 170, false, true),
('Chicken Kabab (Half)', 'Starters', 130, false, true),
('Chicken Kabab (Full)', 'Starters', 250, false, true),
('Chicken Manchurian', 'Starters', 230, false, true),
('Chicken 65', 'Starters', 230, false, true),
('Chilli Chicken', 'Starters', 250, false, true),
('Garlic Chicken', 'Starters', 250, false, true),
('Pepper Chicken', 'Starters', 250, false, true),
('Lemon Chicken', 'Starters', 250, false, true),
('Ginger Chicken', 'Starters', 250, false, true),

-- Shawarma
('Shawarma Roll', 'Shawarma', 90, false, true),
('Shawarma Plate', 'Shawarma', 140, false, true),
('Peri Peri Shawarma Roll', 'Shawarma', 100, false, true),
('Peri Peri Shawarma Plate', 'Shawarma', 150, false, true),

-- Alfam
('Normal Alfam (Quarter)', 'Alfam', 160, false, true),
('Normal Alfam (Half)', 'Alfam', 300, false, true),
('Normal Alfam (Full)', 'Alfam', 570, false, true),
('Peri Peri Alfam (Quarter)', 'Alfam', 200, false, true),
('Peri Peri Alfam (Half)', 'Alfam', 350, false, true),
('Peri Peri Alfam (Full)', 'Alfam', 650, false, true),
('Honey Alfam (Quarter)', 'Alfam', 200, false, true),
('Honey Alfam (Half)', 'Alfam', 350, false, true),
('Honey Alfam (Full)', 'Alfam', 650, false, true),

-- Mandi
('Chicken Mandi (Quarter)', 'Mandi', 200, false, true),
('Chicken Mandi (Half)', 'Mandi', 380, false, true),
('Chicken Mandi (Full)', 'Mandi', 720, false, true),
('Alfam Mandi (Quarter)', 'Mandi', 230, false, true),
('Alfam Mandi (Half)', 'Mandi', 460, false, true),
('Alfam Mandi (Full)', 'Mandi', 760, false, true),
('Peri Peri Alfam Mandi (Quarter)', 'Mandi', 260, false, true),
('Peri Peri Alfam Mandi (Half)', 'Mandi', 480, false, true),
('Peri Peri Alfam Mandi (Full)', 'Mandi', 820, false, true),
('Honey Alfam Mandi (Quarter)', 'Mandi', 260, false, true),
('Honey Alfam Mandi (Half)', 'Mandi', 480, false, true),
('Honey Alfam Mandi (Full)', 'Mandi', 820, false, true),

-- Fried Rice & Noodles
('Veg Fried Rice', 'Fried Rice & Noodles', 150, false, true),
('Veg Noodles', 'Fried Rice & Noodles', 160, false, true),
('Mushroom Fried Rice', 'Fried Rice & Noodles', 160, false, true),
('Mushroom Noodles', 'Fried Rice & Noodles', 170, false, true),
('Paneer Fried Rice', 'Fried Rice & Noodles', 180, false, true),
('Paneer Noodles', 'Fried Rice & Noodles', 210, false, true),
('Egg Fried Rice', 'Fried Rice & Noodles', 170, false, true),
('Egg Noodles', 'Fried Rice & Noodles', 180, false, true),
('Chicken Fried Rice', 'Fried Rice & Noodles', 180, false, true),
('Chicken Noodles', 'Fried Rice & Noodles', 190, false, true),
('Veg Mix Fried Rice', 'Fried Rice & Noodles', 190, false, true),
('Veg Mix Noodles', 'Fried Rice & Noodles', 200, false, true),
('Non Veg Mix Fried Rice', 'Fried Rice & Noodles', 280, false, true),
('Non Veg Mix Noodles', 'Fried Rice & Noodles', 290, false, true),

-- Chinese
('Tomato Fry', 'Chinese', 120, false, true),
('Mix Veg Curry', 'Chinese', 140, false, true),
('Paneer Butter Masala', 'Chinese', 190, false, true),
('Kadai Paneer', 'Chinese', 210, false, true),
('Mushroom Masala', 'Chinese', 190, false, true),
('Butter Chicken', 'Chinese', 270, false, true),
('Kadai Chicken', 'Chinese', 280, false, true),

-- Juice & Shakes
('Pineapple Juice', 'Juice & Shakes', 0, true, true),
('Watermelon Juice', 'Juice & Shakes', 0, true, true),
('Muskmelon Juice', 'Juice & Shakes', 0, true, true),
('Orange Juice', 'Juice & Shakes', 0, true, true),
('Mosambi Juice', 'Juice & Shakes', 0, true, true),
('Grape Pulpi', 'Juice & Shakes', 0, true, true),
('Lime Juice', 'Juice & Shakes', 0, true, true),
('Lime Soda', 'Juice & Shakes', 0, true, true),
('Chikku Shake', 'Juice & Shakes', 0, true, true),
('Mango Shake', 'Juice & Shakes', 0, true, true);
