export function generateReportPDF(reportData) {
  const { date, summary, topItems } = reportData;

  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    alert('Popup blocked! Please allow popups.');
    return;
  }

  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>Nandanam Report - ${date}</title>
      <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'Courier New', monospace; padding: 20px; font-size: 12px; }
        .header { text-align: center; margin-bottom: 20px; border-bottom: 2px solid #000; padding-bottom: 10px; }
        .header h1 { font-size: 18px; letter-spacing: 2px; }
        .header p { font-size: 10px; color: #666; }
        .section { margin-bottom: 15px; }
        .section h2 { font-size: 14px; border-bottom: 1px dashed #000; margin-bottom: 8px; padding-bottom: 4px; }
        .grid { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 10px; }
        .stat { text-align: center; padding: 10px; border: 1px solid #ddd; border-radius: 4px; }
        .stat .value { font-size: 20px; font-weight: bold; }
        .stat .label { font-size: 9px; color: #666; margin-top: 2px; }
        table { width: 100%; border-collapse: collapse; margin-top: 5px; }
        th, td { padding: 5px 8px; text-align: left; border-bottom: 1px solid #eee; font-size: 11px; }
        th { font-weight: bold; background: #f5f5f5; }
        .total-row { font-weight: bold; border-top: 2px solid #000; }
        .footer { text-align: center; margin-top: 20px; font-size: 9px; color: #999; }
        @media print { body { padding: 10px; } }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>NANDANAM RESTAURANT</h1>
        <p>Ananda Nagar, Electronic City, Bengaluru</p>
        <p style="margin-top:5px; font-size:12px; font-weight:bold;">Daily Report — ${date}</p>
      </div>

      <div class="section">
        <h2>Summary</h2>
        <div class="grid">
          <div class="stat">
            <div class="value">${summary.totalOrders}</div>
            <div class="label">Total Orders</div>
          </div>
          <div class="stat">
            <div class="value">₹${summary.totalRevenue}</div>
            <div class="label">Total Revenue</div>
          </div>
          <div class="stat">
            <div class="value">₹${summary.avgOrderValue}</div>
            <div class="label">Avg Order Value</div>
          </div>
        </div>
      </div>

      ${topItems.length > 0 ? `
      <div class="section">
        <h2>Top Ordered Items</h2>
        <table>
          <thead>
            <tr><th>#</th><th>Item</th><th>Qty Sold</th><th>Revenue</th></tr>
          </thead>
          <tbody>
            ${topItems.map((item, i) => `
              <tr>
                <td>${i + 1}</td>
                <td>${item.name}</td>
                <td>${item.totalQty}</td>
                <td>₹${item.totalRevenue}</td>
              </tr>
            `).join('')}
          </tbody>
        </table>
      </div>
      ` : ''}

      <div class="footer">
        Generated by Nandanam Order System
      </div>
      <script>window.onload = function() { window.print(); }</script>
    </body>
    </html>
  `;

  printWindow.document.write(html);
  printWindow.document.close();
}
